## Python libraries

### Numpy

In [3]:
# Create 1D Array
import numpy
x=numpy.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [2]:
type(x)

numpy.ndarray

In [4]:
# Create 2D Array
import numpy as np
y=np.array([[1,2,3],[4,5,6]])
print(y)
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)

[[1 2 3]
 [4 5 6]]


In [50]:
# Create 3D Array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
a=([[1,2,3],[4,5,6],[7,8,9]])
z1=np.array(a)
print(z)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
z[0]

array([1, 2, 3])

In [10]:
z[0][0]

1

In [13]:
z[1][0]

4

In [14]:
z[2][2]

9

In [17]:
z.shape

(3, 3)

In [18]:
z.size

9

In [49]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)



[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [43]:
arr[0]

1

In [47]:
arr[0][1]

array([4, 5, 6])

In [48]:
arr[0][1][0]

4

In [28]:
import numpy as np

r = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [29]:
s=np.array([1,2,3,4,5,6],dtype=complex)
s

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

### Array Slicing

In [32]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x[5:]

array([6, 7, 8, 9])

In [34]:
x[::2]

array([1, 3, 5, 7, 9])

In [35]:
x[1::2]

array([2, 4, 6, 8])

In [36]:
x[1:7:2]

array([2, 4, 6])

In [37]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [38]:
x[5::-2]

array([6, 4, 2])

In [53]:
arr.shape

(2, 2, 3)

In [54]:
arr.size

12

In [55]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr1.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [57]:
newarr1=x.reshape(3,3)
newarr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Concatenation of Arrays

In [59]:
p=np.array([1,2,3])
q=np.array([4,5,6])
r1=np.concatenate([p,q])
r1

array([1, 2, 3, 4, 5, 6])

## Splitting of Arrays

In [61]:
import numpy as np
y1 = np.arange(9)
print(y1)
print(np.split(y1, 3))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [63]:
a1,a2,a3=(np.split(y1,[3,6]))
print(a1,a2,a3)

[0 1 2] [3 4 5] [6 7 8]


In [66]:
a5=np.arange(49).reshape(7,7)
a5

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [65]:
a4=np.arange(10000).reshape(100,100)
a4

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [67]:
a6=np.arange(12).reshape(2,6)
a6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [68]:
a7=np.ones((3,3))
a7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
a8=a7-1
a8

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
a9=a7+4
a9

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [71]:
a10=[1,2,3,4]
print(np.sin(a10))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [72]:
print(np.cos(a10))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [73]:
print(np.sqrt(a10))

[1.         1.41421356 1.73205081 2.        ]


In [74]:
print(np.tan(a10))

[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [79]:
import numpy as np  
a11=np.random.rand(4,3)  
a11  

array([[0.7688825 , 0.38608348, 0.90383823],
       [0.38167114, 0.48596455, 0.71164461],
       [0.01887273, 0.61969903, 0.32742094],
       [0.45486141, 0.8351554 , 0.68876444]])

In [82]:
import numpy as np  
a12=np.random.randint(4, size=10)  
a12  

array([0, 1, 1, 1, 0, 0, 1, 3, 2, 3])

In [83]:
a13=np.random.ranf(4,)  
a13  

array([0.5133108 , 0.7405695 , 0.33367741, 0.33125813])