## Python libraries

### Numpy

In [3]:
# Create 1D Array
import numpy
x=numpy.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [2]:
type(x)

numpy.ndarray

In [4]:
# Create 2D Array
import numpy as np
y=np.array([[1,2,3],[4,5,6]])
print(y)
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)

[[1 2 3]
 [4 5 6]]


In [50]:
# Create 3D Array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
a=([[1,2,3],[4,5,6],[7,8,9]])
z1=np.array(a)
print(z)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
z[0]

array([1, 2, 3])

In [10]:
z[0][0]

1

In [13]:
z[1][0]

4

In [14]:
z[2][2]

9

In [17]:
z.shape

(3, 3)

In [18]:
z.size

9

In [49]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)



[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [43]:
arr[0]

1

In [47]:
arr[0][1]

array([4, 5, 6])

In [48]:
arr[0][1][0]

4

In [28]:
import numpy as np

r = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [29]:
s=np.array([1,2,3,4,5,6],dtype=complex)
s

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

### Array Slicing

In [32]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x[5:]

array([6, 7, 8, 9])

In [34]:
x[::2]

array([1, 3, 5, 7, 9])

In [35]:
x[1::2]

array([2, 4, 6, 8])

In [36]:
x[1:7:2]

array([2, 4, 6])

In [37]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [38]:
x[5::-2]

array([6, 4, 2])

In [53]:
arr.shape

(2, 2, 3)

In [54]:
arr.size

12

In [55]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr1.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [57]:
newarr1=x.reshape(3,3)
newarr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Concatenation of Arrays

In [59]:
p=np.array([1,2,3])
q=np.array([4,5,6])
r1=np.concatenate([p,q])
r1

array([1, 2, 3, 4, 5, 6])

## Splitting of Arrays

In [61]:
import numpy as np
y1 = np.arange(9)
print(y1)
print(np.split(y1, 3))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [63]:
a1,a2,a3=(np.split(y1,[3,6]))
print(a1,a2,a3)

[0 1 2] [3 4 5] [6 7 8]
