In [1]:
import numpy as np
a= np.array([41, 42, 43, 44])
x= [True, False, True, False]
newarr = a[x]
print(newarr)

[41 43]


In [2]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr1 % 2 == 0

newarr1 = arr1[filter_arr]

print(filter_arr)
print(newarr1)

[False  True False  True False  True False]
[2 4 6]


### Statistical Arrays

In [12]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])  
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [13]:
print(np.amin(a,1))   

[3 3 2]


In [6]:
print(np.amin(a,0)) 

[2 4 3]


In [7]:
print(np.amax(a))

9


In [10]:
print(np.amin(a, axis = 0))

[2 4 3]
