### Today Agenda is Panda

## Pandas having two mechanisms:
### 1.Series
### 2.Dataframes

In [8]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'1.1.3'

### To check functionalities inside pandas

In [5]:
print(len(dir(pd)))

140


In [6]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p16', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'comp

#### If you import all the funtions for simple calculations it increase the space complexity and time complexity
#### So best way to import functionalities is to import particular funtion that use for us

In [12]:
m=np.arange?
# to have description about that function

In [27]:
m=np.arange(30,100,10)
m
#Here 30 is inclusive and 100 is exclusive

array([30, 40, 50, 60, 70, 80, 90])

In [9]:
mydata=np.arange(30,100)
mydata

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
       81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
       98, 99])

In [23]:
type(g.values)

numpy.ndarray

In [24]:
g.values

array([35.456, 67.467, 98.356, 89.636, 56.588])

In [25]:
g.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
g.index=['canada','germany','italy','france','unitedkingdom']
g


canada           35.456
germany          67.467
italy            98.356
france           89.636
unitedkingdom    56.588
dtype: float64

In [7]:
# In millions
g=pd.Series([35.456,67.467,98.356,89.636,56.588])
g

0    35.456
1    67.467
2    98.356
3    89.636
4    56.588
dtype: float64

In [14]:
m1=pd.Series(mydata)
m1

0     30
1     31
2     32
3     33
4     34
      ..
65    95
66    96
67    97
68    98
69    99
Length: 70, dtype: int32

In [17]:
m1.name="population"

In [18]:
m1.dtype

dtype('int32')

In [19]:
m1[0]

30

In [20]:
m1[1:4]

1    31
2    32
3    33
Name: population, dtype: int32

In [21]:
m1[1:7:2]

1    31
3    33
5    35
Name: population, dtype: int32

In [22]:
m1[::3]

0     30
3     33
6     36
9     39
12    42
15    45
18    48
21    51
24    54
27    57
30    60
33    63
36    66
39    69
42    72
45    75
48    78
51    81
54    84
57    87
60    90
63    93
66    96
69    99
Name: population, dtype: int32